# Generated by Django 5.2.3 on 2025-09-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default='Немає опису'),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('В продажі', 'в продажі'), ('Продано', 'продано')], default='В продажі', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Немає назви', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
