# Generated by Django 5.2.3 on 2025-09-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_description_booking_first_data_booking_owner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Вiary',
        ),
    ]
