# Generated by Django 5.2.3 on 2025-09-25 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forum_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
