# Generated by Django 5.2.3 on 2025-09-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_forum_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
