# Generated by Django 5.2.3 on 2025-09-26 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
