# Generated by Django 5.2.3 on 2025-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_forum_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
