# Generated by Django 5.2.3 on 2025-09-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_forum_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
