# Generated by Django 5.2.3 on 2025-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_scheduleentry_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_user',
            field=models.CharField(choices=[('Вчитель', 'вчитель'), ('Студент', 'студент')], default='Користувач', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Користувач', 'користувач'), ('Модератор', 'модератор'), ('Адміністратор', 'адміністратор')], default='Користувач', max_length=20),
        ),
    ]
