# Generated by Django 5.2.3 on 2025-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_role_user_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_user',
            field=models.CharField(choices=[('Вчитель', 'вчитель'), ('Студент', 'студент')], default='Студент', max_length=20),
        ),
    ]
