# Generated by Django 5.2.3 on 2025-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_role_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
