# Generated by Django 5.2.3 on 2025-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_scheduleentry_room_alter_scheduleentry_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
