# Generated by Django 5.2.3 on 2025-10-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_comment_event_alter_comment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
