# Generated by Django 5.2.3 on 2025-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
    ]
