# Generated by Django 5.2.3 on 2025-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_grade_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='lesson',
            field=models.CharField(choices=[('Українська мова', 'Українська мова'), ('Математика', 'Математика'), ('Біологія', 'Біологія')], default='Українська мова', max_length=20),
        ),
    ]
