# Generated by Django 5.2.3 on 2025-10-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_grade_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(choices=[('Українська мова', 'Українська мова'), ('Математика', 'Математика'), ('Біологія', 'Біологія')], default='Українська мова', max_length=20),
        ),
    ]
