# Generated by Django 5.2.3 on 2025-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_grade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subject_text',
            field=models.CharField(default='Немає уроку', max_length=50),
        ),
    ]
