# Generated by Django 5.2.3 on 2025-10-10 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_grade_subject_alter_grade_subject_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('title', models.CharField(max_length=100)),
                ('quest', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poll_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
