# Generated by Django 5.2.3 on 2025-10-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_grade_student_name_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.poll'),
        ),
    ]
