# Generated by Django 5.2.3 on 2025-10-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_comment_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='poll',
        ),
    ]
