# Generated by Django 5.2.3 on 2025-10-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_poll_quest_alter_poll_owner_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
